### ISSUE TITLE
Loop & Filters

### ISSUE THREAD

**Issue by apidev234** [lukasl-dev/waterlink#12]
How can i enable looping the queue and adding filters to the music?

**Comment by lukasl-dev** [comment]
Looping can be implemented manually by listening for incoming events. This effectively means that when a TrackEnd event arrives, the track can be played again.

```go
package main

import (
	"github.com/lukasl-dev/waterlink/v2"
	"github.com/lukasl-dev/waterlink/v2/event"
)

func main() {
	creds := waterlink.Credentials{
		Authorization: "youshallnotpass",
		UserID:        0,
	}

	var conn *waterlink.Connection
	opts := waterlink.ConnectionOptions{
		EventHandler: waterlink.EventHandlerFunc(func(evt interface{}) {
			switch evt := evt.(type) {
			case event.TrackEnd:
				_ = conn.Guild(evt.GuildID).Play(evt.TrackID)
			}
		}),
	}

	conn, _ = waterlink.Open("ws://localhost:2333", creds, opts)
}
```

The filters will be added to the library soon. I wanted to look into this in more detail so that potential bugs can be prevented at release.

**Comment by apidev234** [comment]
Alright, Thanks!
